SELECT COUNT (*) 전체행수, COUNT (HEIGHT) 키건수, MAX (HEIGHT) 최대키, MIN (HEIGHT) 최소키, ROUND (AVG (HEIGHT),2) 평균키
FROM PLAYER;

SELECT POSITION 포지션, AVG (HEIGHT) 평균키
FROM PLAYER
GROUP BY 포지션;

SELECT POSITION 포지션, COUNT (*) 인원수, 
       COUNT (HEIGHT) 키대상, 
       MAX (HEIGHT) 최대키, 
       MIN (HEIGHT) 최소키, 
       ROUND (AVG (HEIGHT))
FROM PLAYER
GROUP BY POSITION;

SELECT POSITION 포지션, ROUND (AVG(HEIGHT),2) 평균키
FROM PLAYER
GROUP BY POSITION
HAVING AVG(HEIGHT)>=180;

SELECT POSITION 포지션, AVG(HEIGHT) 평균키
FROM PLAYER
HAVING AVG(HEIGHT)>=180
GROUP BY POSITION;

SELECT TEAM_ID 팀ID, COUNT (*) 인원수
FROM PLAYER
GROUP BY TEAM_ID
HAVING TEAM_ID IN ('K02', 'K09');

SELECT POSITION 포지션, ROUND(AVG(HEIGHT),2) 평균키, MAX(HEIGHT)
FROM PLAYER
GROUP BY POSITION
HAVING MAX(HEIGHT)>=190;

SELECT ENAME 사원명, DEPTNO 부서번호, EXTRACT (MONTH FROM HIREDATE) 입사월, SAL 급여
FROM EMP;